#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Espera.Android.Resource", IsApplication=true)]

namespace Espera.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::Espera.Android.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int preference_administrator_default_library_action_entries = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int ga_autoActivityTracking = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ga_reportUncaughtExceptions = 2131034113;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CurrentSongIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Next = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Pause = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Play = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Previous = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Settings = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int ArtistList = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int ConnectButton = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int Image = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int LoadArtistsButton = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int LoadCurrentPlaylistButton = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int LocalSongAlbum = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int LocalSongTitle = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int LocalSongTransferProgress = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int LocalSongsButton = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int NextButton = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int PlayList = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int PlayPauseButton = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int PlaybackControlPanel = 2131165194;
			
			// aapt resource value: 0x7f070010
			public const int PlaylistEntryArtist = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int PlaylistEntryTitle = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int PreviousButton = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int SongsList = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Artists = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LocalSongItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LocalSongs = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Playlist = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlaylistListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RemoteSongs = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ga_trackingId = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int preference_administrator_default_library_action_summary = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int preference_administrator_default_library_action_title = 2130968589;
			
			// aapt resource value: 0x7f040007
			public const int preference_administrator_mode = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int preference_administrator_mode_summary = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int preference_administrator_mode_title = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int preference_administrator_password = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int preference_administrator_password_title = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int preference_default_library_action = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int preference_port = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int preference_port_summary = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int preference_port_title = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int preference_port_validation_error = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
