#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Espera.Android.Resource", IsApplication=true)]

namespace Espera.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::Espera.Android.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int preference_administrator_default_library_action_entries = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int ga_autoActivityTracking = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ga_reportUncaughtExceptions = 2131034113;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080004
			public const int accent = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int black = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int dark = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int gray = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int white = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CurrentSongIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int mahapps_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int mahapps_button_text = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Next = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Pause = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Play = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Previous = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Settings = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int ArtistList = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int ConnectButton = 2131296261;
			
			// aapt resource value: 0x7f09000c
			public const int CurrentTimeTextView = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int DurationSeekBar = 2131296269;
			
			// aapt resource value: 0x7f090012
			public const int Image = 2131296274;
			
			// aapt resource value: 0x7f090008
			public const int LoadLocalArtistsButton = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int LoadPlaylistButton = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int LoadRemoteArtistsButton = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int LocalSongAlbum = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int LocalSongTitle = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int LocalSongTransferProgress = 2131296259;
			
			// aapt resource value: 0x7f090011
			public const int NextButton = 2131296273;
			
			// aapt resource value: 0x7f09000a
			public const int PlayList = 2131296266;
			
			// aapt resource value: 0x7f090010
			public const int PlayPauseButton = 2131296272;
			
			// aapt resource value: 0x7f09000b
			public const int PlaybackControlPanel = 2131296267;
			
			// aapt resource value: 0x7f090014
			public const int PlaylistEntryArtist = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int PlaylistEntryTitle = 2131296275;
			
			// aapt resource value: 0x7f09000f
			public const int PreviousButton = 2131296271;
			
			// aapt resource value: 0x7f090004
			public const int SongsList = 2131296260;
			
			// aapt resource value: 0x7f09000e
			public const int TotalTimeTextView = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int TrialExpirationTextView = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Artists = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LocalSongItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LocalSongs = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Playlist = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlaylistListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RemoteSongs = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Settings = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ga_trackingId = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int preference_administrator_default_library_action_summary = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int preference_administrator_default_library_action_title = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int preference_administrator_password = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int preference_administrator_password_title = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int preference_default_library_action = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int preference_ipaddress = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int preference_ipaddress_summary = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int preference_ipaddress_title = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int preference_ipaddress_validation_error = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int preference_port = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int preference_port_summary = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int preference_port_title = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int preference_port_validation_error = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int preference_save_energy = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int preference_save_energy_summary = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int preference_save_energy_title = 2130968588;
			
			// aapt resource value: 0x7f040013
			public const int trial_expiration = 2130968595;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_MahApps = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_MahApps_ActionBar = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Theme_MahApps_Widget_Button = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
