#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Espera.Android.Resource", IsApplication=true)]

namespace Espera.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Espera.Android.Resource.String.library_name;
			global::Splat.Resource.String.library_name = global::Espera.Android.Resource.String.library_name;
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::Espera.Android.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::Espera.Android.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int preference_administrator_default_library_action_entries = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int ga_autoActivityTracking = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ga_reportUncaughtExceptions = 2131034113;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080004
			public const int accent = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int accent4 = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int black = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int dark = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int gray = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int white = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CurrentSongIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Feedback = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_drawer = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mahapps_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mahapps_button_text = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Next = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Pause = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Play = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Previous = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Settings = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int VideoPlayer = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int ArtistList = 2131361792;
			
			// aapt resource value: 0x7f0a001d
			public const int Artwork = 2131361821;
			
			// aapt resource value: 0x7f0a0001
			public const int ConnectButton = 2131361793;
			
			// aapt resource value: 0x7f0a000a
			public const int ContentFrame = 2131361802;
			
			// aapt resource value: 0x7f0a0012
			public const int CurrentTimeTextView = 2131361810;
			
			// aapt resource value: 0x7f0a000d
			public const int DetailImage = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int DetailText = 2131361806;
			
			// aapt resource value: 0x7f0a0013
			public const int DurationSeekBar = 2131361811;
			
			// aapt resource value: 0x7f0a0018
			public const int Image = 2131361816;
			
			// aapt resource value: 0x7f0a0006
			public const int LocalSongAlbum = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int LocalSongTitle = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int LocalSongTransferProgress = 2131361799;
			
			// aapt resource value: 0x7f0a0009
			public const int MainDrawer = 2131361801;
			
			// aapt resource value: 0x7f0a000b
			public const int MainDrawerListView = 2131361803;
			
			// aapt resource value: 0x7f0a0017
			public const int NextButton = 2131361815;
			
			// aapt resource value: 0x7f0a0010
			public const int PlayList = 2131361808;
			
			// aapt resource value: 0x7f0a0016
			public const int PlayPauseButton = 2131361814;
			
			// aapt resource value: 0x7f0a0011
			public const int PlaybackControlPanel = 2131361809;
			
			// aapt resource value: 0x7f0a001a
			public const int PlaylistEntryArtist = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int PlaylistEntryDuration = 2131361819;
			
			// aapt resource value: 0x7f0a0019
			public const int PlaylistEntryTitle = 2131361817;
			
			// aapt resource value: 0x7f0a0015
			public const int PreviousButton = 2131361813;
			
			// aapt resource value: 0x7f0a000c
			public const int PrimaryItemText = 2131361804;
			
			// aapt resource value: 0x7f0a000f
			public const int ProgressSpinner = 2131361807;
			
			// aapt resource value: 0x7f0a0008
			public const int SongsList = 2131361800;
			
			// aapt resource value: 0x7f0a001f
			public const int SoundCloudSongArtist = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int SoundCloudSongPlaybackCount = 2131361824;
			
			// aapt resource value: 0x7f0a001e
			public const int SoundCloudSongTitle = 2131361822;
			
			// aapt resource value: 0x7f0a001c
			public const int SoundCloudSongsList = 2131361820;
			
			// aapt resource value: 0x7f0a0025
			public const int ToggleVideoPlayer = 2131361829;
			
			// aapt resource value: 0x7f0a0014
			public const int TotalTimeTextView = 2131361812;
			
			// aapt resource value: 0x7f0a0002
			public const int TrialContainer = 2131361794;
			
			// aapt resource value: 0x7f0a0004
			public const int TrialExpirationExplanationTextView = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int TrialExpirationTextView = 2131361795;
			
			// aapt resource value: 0x7f0a0022
			public const int YoutubeSongTitle = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int YoutubeSongUploader = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int YoutubeSongViews = 2131361828;
			
			// aapt resource value: 0x7f0a0021
			public const int YoutubeSongsList = 2131361825;
			
			// aapt resource value: 0x7f0a0026
			public const int search = 2131361830;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Artists = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConnectionLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LocalSongItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LocalSongs = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainDrawerDivider = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainDrawerPrimaryItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainDrawerSecondaryItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Playlist = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PlaylistListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RemoteSongs = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Settings = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SoundCloud = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SoundCloudSongItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Youtube = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int YoutubeSongItem = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int PlaylistMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int SearchMenu = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04003b
			public const int add_to_playlist = 2130968635;
			
			// aapt resource value: 0x7f040064
			public const int added_to_playlist = 2130968676;
			
			// aapt resource value: 0x7f040031
			public const int administrator_functions = 2130968625;
			
			// aapt resource value: 0x7f04006d
			public const int artists_no_songs = 2130968685;
			
			// aapt resource value: 0x7f040057
			public const int connect = 2130968663;
			
			// aapt resource value: 0x7f04004a
			public const int connected_as_admin = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int connected_as_guest = 2130968651;
			
			// aapt resource value: 0x7f040056
			public const int connecting = 2130968662;
			
			// aapt resource value: 0x7f040049
			public const int connection_failed = 2130968649;
			
			// aapt resource value: 0x7f04004f
			public const int connection_lost = 2130968655;
			
			// aapt resource value: 0x7f040044
			public const int connection_timeout = 2130968644;
			
			// aapt resource value: 0x7f040055
			public const int disconnect = 2130968661;
			
			// aapt resource value: 0x7f040065
			public const int error_adding_song = 2130968677;
			
			// aapt resource value: 0x7f040063
			public const int error_adding_songs = 2130968675;
			
			// aapt resource value: 0x7f040003
			public const int ga_trackingId = 2130968579;
			
			// aapt resource value: 0x7f040030
			public const int guest_functions = 2130968624;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040041
			public const int loading_artists = 2130968641;
			
			// aapt resource value: 0x7f040058
			public const int loading_artists_failed = 2130968664;
			
			// aapt resource value: 0x7f04003c
			public const int loading_playlist = 2130968636;
			
			// aapt resource value: 0x7f04005c
			public const int loading_playlist_failed = 2130968668;
			
			// aapt resource value: 0x7f040066
			public const int loading_soundcloud = 2130968678;
			
			// aapt resource value: 0x7f040069
			public const int loading_youtube = 2130968681;
			
			// aapt resource value: 0x7f040060
			public const int local_artists = 2130968672;
			
			// aapt resource value: 0x7f040038
			public const int local_artists_fragment_title = 2130968632;
			
			// aapt resource value: 0x7f040037
			public const int local_songs = 2130968631;
			
			// aapt resource value: 0x7f040025
			public const int main_drawer_connection = 2130968613;
			
			// aapt resource value: 0x7f04002c
			public const int main_drawer_feedback = 2130968620;
			
			// aapt resource value: 0x7f040028
			public const int main_drawer_local_songs = 2130968616;
			
			// aapt resource value: 0x7f040026
			public const int main_drawer_playlist = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int main_drawer_remote_songs = 2130968615;
			
			// aapt resource value: 0x7f04002b
			public const int main_drawer_settings = 2130968619;
			
			// aapt resource value: 0x7f040029
			public const int main_drawer_soundcloud = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int main_drawer_youtube = 2130968618;
			
			// aapt resource value: 0x7f040032
			public const int main_fragment_title = 2130968626;
			
			// aapt resource value: 0x7f040040
			public const int move_down = 2130968640;
			
			// aapt resource value: 0x7f04003f
			public const int move_up = 2130968639;
			
			// aapt resource value: 0x7f040039
			public const int no_votes_left = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int play = 2130968634;
			
			// aapt resource value: 0x7f04005b
			public const int playback_failed = 2130968667;
			
			// aapt resource value: 0x7f04005a
			public const int playing_song = 2130968666;
			
			// aapt resource value: 0x7f040062
			public const int playing_songs = 2130968674;
			
			// aapt resource value: 0x7f040033
			public const int playlist = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int playlist_fragment_title = 2130968628;
			
			// aapt resource value: 0x7f04003d
			public const int playlist_is_empty = 2130968637;
			
			// aapt resource value: 0x7f040014
			public const int preference_administrator_default_library_action_summary = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int preference_administrator_default_library_action_title = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int preference_administrator_password = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int preference_administrator_password_summary = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int preference_administrator_password_title = 2130968593;
			
			// aapt resource value: 0x7f040024
			public const int preference_category_about = 2130968612;
			
			// aapt resource value: 0x7f040022
			public const int preference_category_administrator = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int preference_category_network = 2130968609;
			
			// aapt resource value: 0x7f040023
			public const int preference_category_premium = 2130968611;
			
			// aapt resource value: 0x7f04001f
			public const int preference_development = 2130968607;
			
			// aapt resource value: 0x7f040009
			public const int preference_ipaddress = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int preference_ipaddress_summary = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int preference_ipaddress_title = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int preference_ipaddress_validation_error = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int preference_main_screen = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int preference_port = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int preference_port_summary = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int preference_port_title = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int preference_port_validation_error = 2130968584;
			
			// aapt resource value: 0x7f040017
			public const int preference_purchase_premium = 2130968599;
			
			// aapt resource value: 0x7f040019
			public const int preference_purchase_premium_summary = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int preference_purchase_premium_title = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int preference_restore_premium = 2130968602;
			
			// aapt resource value: 0x7f04001c
			public const int preference_restore_premium_summary = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int preference_restore_premium_title = 2130968603;
			
			// aapt resource value: 0x7f04000d
			public const int preference_save_energy = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int preference_save_energy_summary = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int preference_save_energy_title = 2130968590;
			
			// aapt resource value: 0x7f040016
			public const int preference_switch_no = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int preference_switch_yes = 2130968597;
			
			// aapt resource value: 0x7f04001d
			public const int preference_version = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int preference_version_title = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int preference_virtual_server = 2130968608;
			
			// aapt resource value: 0x7f040043
			public const int premium_already_purchased = 2130968643;
			
			// aapt resource value: 0x7f040046
			public const int purchase_failed = 2130968646;
			
			// aapt resource value: 0x7f040048
			public const int purchase_restore_failed = 2130968648;
			
			// aapt resource value: 0x7f040047
			public const int purchase_restored = 2130968647;
			
			// aapt resource value: 0x7f040045
			public const int purchase_successful = 2130968645;
			
			// aapt resource value: 0x7f040061
			public const int remote_artists = 2130968673;
			
			// aapt resource value: 0x7f040036
			public const int remote_artists_fragment_title = 2130968630;
			
			// aapt resource value: 0x7f040035
			public const int remote_songs = 2130968629;
			
			// aapt resource value: 0x7f04003e
			public const int remove = 2130968638;
			
			// aapt resource value: 0x7f04004c
			public const int required_server_version = 2130968652;
			
			// aapt resource value: 0x7f04006c
			public const int search = 2130968684;
			
			// aapt resource value: 0x7f04006f
			public const int service_notification_text = 2130968687;
			
			// aapt resource value: 0x7f04006e
			public const int service_notification_title = 2130968686;
			
			// aapt resource value: 0x7f04004e
			public const int settings = 2130968654;
			
			// aapt resource value: 0x7f040059
			public const int something_went_wrong = 2130968665;
			
			// aapt resource value: 0x7f040067
			public const int soundcloud_no_songs = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int soundcloud_play = 2130968680;
			
			// aapt resource value: 0x7f040070
			public const int toggle_video_player = 2130968688;
			
			// aapt resource value: 0x7f04002d
			public const int trial_expiration = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int trial_expiration_expired = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int trial_expiration_explanation = 2130968623;
			
			// aapt resource value: 0x7f040042
			public const int uses_vote = 2130968642;
			
			// aapt resource value: 0x7f04005e
			public const int vote = 2130968670;
			
			// aapt resource value: 0x7f04005d
			public const int vote_failed = 2130968669;
			
			// aapt resource value: 0x7f04005f
			public const int votes_and_votes_left = 2130968671;
			
			// aapt resource value: 0x7f040054
			public const int wifi_enable_error = 2130968660;
			
			// aapt resource value: 0x7f040053
			public const int wifi_enable_later = 2130968659;
			
			// aapt resource value: 0x7f040052
			public const int wifi_enable_now = 2130968658;
			
			// aapt resource value: 0x7f040051
			public const int wifi_reminder_message = 2130968657;
			
			// aapt resource value: 0x7f040050
			public const int wifi_reminder_title = 2130968656;
			
			// aapt resource value: 0x7f04004d
			public const int wrong_password = 2130968653;
			
			// aapt resource value: 0x7f04006a
			public const int youtube_no_songs = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int youtube_view = 2130968683;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_MahApps = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_MahApps_ActionBar = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Theme_MahApps_Widget_Button = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Theme_MahApps_Widget_TextView = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
